### ISSUE TITLE
how to use ts file make release js file.

### ISSUE THREAD

**Issue by xboy2006** [jcyuan/FairyGUI-PixiJS#38]
how to use ts file make Production js file(like fairygui.min.js).

**Comment by jcyuan** [comment]
please find some vscode tutorials on Google.
in the tsconfig.json you can specify what module you would like to build.
one single file or seperated files.
that's why I removed the project build config last time.
you can probably add you own task into the tasks.json say webpack, once the vscode compile and js files are outputed, run webpack task to pack what you want.

@xboy2006 

so close this issue.

**Comment by xboy2006** [comment]
thx.
